apiVersion: v1
kind: Pod
metadata:
  labels:
    test: liveness-api
  name: liveness-http

spec:
  ports:
  - name: api-port
    containerPort: 8080
    hostPort: 8080
  containers:

  - name: liveness-api
    image: registry.k8s.io/liveness
    args:
    - /server

    livenessProbe:
      httpGet:
        path: /healthcheck/live
        port: api-port
      initialDelaySeconds: 3
      failureThreshold: 1
      periodSeconds: 3
    startupProbe:
      httpGet:
        path: /healthcheck/ready
        port: api-port
      failureThreshold: 30
      periodSeconds: 10
    readinessProbe:
      httpGet:
        path: /healthcheck/ready
        port: api-port
      failureThreshold: 30
      periodSeconds: 10
