apiVersion: v1
kind: Pod
metadata:
  labels:
    test: liveness
  name: liveness-http

spec:
  ports:
  - name: liveness-port
    containerPort: 8080
    hostPort: 8080
  containers:

  - name: liveness
    image: registry.k8s.io/liveness
    args:
    - /server

    livenessProbe:
      httpGet:
        path: /healthz/live
        port: liveness-port
      initialDelaySeconds: 3
      failureThreshold: 1
      periodSeconds: 3
    startupProbe:
      httpGet:
        path: /healthz/ready
        port: liveness-port
      failureThreshold: 30
      periodSeconds: 10
    readinessProbe:
      httpGet:
        path: /healthz/ready
        port: liveness-port
      failureThreshold: 30
      periodSeconds: 10
