version: '3.4'

services:
  healthcare.apigateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "80"
      - "443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
  
  mobilegw:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "7245:80"
    volumes:
      - ./src/HealthCare/Mobile.Bff/apigw:/app/configuration

  webappgw:
   environment:
     - ASPNETCORE_ENVIRONMENT=Development
   ports:
     - "7245:80"
   volumes:
     - ./src/ApiGateways/Web.Bff/apigw:/app/configuration
